import re

def generate_i18n():
    return """
const i18n = {
  'zh-CN': { title: '优必答 知识库', subtitle: '向本地知识库提问。', placeholder: '输入您的问题', teamLabel: '团队 (知识库)', langLabel: '回答语言', askBtn: '提问', newConvBtn: '新对话', hint: '在此浏览器中的后续问题会保留近期的对话上下文。“新对话”会清除该上下文。', waiting: '等待 Worker 处理中...', healthChecking: '正在检查 Worker...', healthOnline: 'Worker 在线', healthOffline: 'Worker 离线', signIn: '登录', manageSources: '管理源文件', uploadDocs: '上传文档', newConvStarted: '已开始新对话。',
    'lang_zh-CN': '简体中文', 'lang_zh-TW': '繁体中文', 'lang_ko': '韩语', 'lang_ja': '日语', 'lang_en': '英语', 'lang_pt': '葡萄牙语', 'lang_ru': '俄语', 'lang_es': '西班牙语' },
  'zh-TW': { title: '優必答 知識庫', subtitle: '向本地知識庫提問。', placeholder: '輸入您的問題', teamLabel: '團隊 (知識庫)', langLabel: '回答語言', askBtn: '提問', newConvBtn: '新對話', hint: '在此瀏覽器中的後續問題會保留近期的對話上下文。“新對話”會清除該上下文。', waiting: '等待 Worker 處理中...', healthChecking: '正在檢查 Worker...', healthOnline: 'Worker 在線', healthOffline: 'Worker 離線', signIn: '登入', manageSources: '管理來源', uploadDocs: '上傳文件', newConvStarted: '已開始新對話。',
    'lang_zh-CN': '簡體中文', 'lang_zh-TW': '繁體中文', 'lang_ko': '韓語', 'lang_ja': '日語', 'lang_en': '英語', 'lang_pt': '葡萄牙語', 'lang_ru': '俄語', 'lang_es': '西班牙語' },
  'ko': { title: 'Uchat 지식 베이스', subtitle: '로컬 위키에 질문하세요.', placeholder: '질문을 입력하세요', teamLabel: '팀 (지식 베이스)', langLabel: '답변 언어', askBtn: '질문하기', newConvBtn: '새 대화', hint: '이 브라우저에서 후속 질문은 최근 대화 컨텍스트를 유지합니다. “새 대화”를 누르면 초기화됩니다.', waiting: '워커 대기 중...', healthChecking: '워커 확인 중...', healthOnline: '워커 온라인', healthOffline: '워커 오프라인', signIn: '로그인', manageSources: '소스 관리', uploadDocs: '문서 업로드', newConvStarted: '새 대화가 시작되었습니다.',
    'lang_zh-CN': '중국어 간체', 'lang_zh-TW': '중국어 번체', 'lang_ko': '한국어', 'lang_ja': '일본어', 'lang_en': '영어', 'lang_pt': '포르투갈어', 'lang_ru': '러시아어', 'lang_es': '스페인어' },
  'ja': { title: 'Uchat ナレッジベース', subtitle: 'ローカルのWikiに質問する', placeholder: '質問を入力してください', teamLabel: 'チーム (ナレッジベース)', langLabel: '回答の言語', askBtn: '質問する', newConvBtn: '新しい会話', hint: 'このブラウザでのフォローアップ質問は、最近の会話のコンテキストを保持します。「新しい会話」でリセットされます。', waiting: 'ワーカーを待機中...', healthChecking: 'ワーカーを確認中...', healthOnline: 'ワーカーオンライン', healthOffline: 'ワーカーオフライン', signIn: 'サインイン', manageSources: 'ソースの管理', uploadDocs: 'ドキュメントのアップロード', newConvStarted: '新しい会話が開始されました。',
    'lang_zh-CN': '簡体字中国語', 'lang_zh-TW': '繁体字中国語', 'lang_ko': '韓国語', 'lang_ja': '日本語', 'lang_en': '英語', 'lang_pt': 'ポルトガル語', 'lang_ru': 'ロシア語', 'lang_es': 'スペイン語' },
  'en': { title: 'Uchat Knowledge Base', subtitle: 'Ask questions against the local wiki.', placeholder: 'Enter a question', teamLabel: 'Team (Knowledge Base)', langLabel: 'Answer language', askBtn: 'Ask', newConvBtn: 'New conversation', hint: 'Follow-up questions in this browser keep recent conversation context. “New conversation” clears that context.', waiting: 'Waiting for Worker...', healthChecking: 'Checking Worker...', healthOnline: 'Worker online', healthOffline: 'Worker offline', signIn: 'Sign in', manageSources: 'Manage sources', uploadDocs: 'Upload documentation', newConvStarted: 'New conversation started.',
    'lang_zh-CN': 'Simplified Chinese', 'lang_zh-TW': 'Traditional Chinese', 'lang_ko': 'Korean', 'lang_ja': 'Japanese', 'lang_en': 'English', 'lang_pt': 'Portuguese', 'lang_ru': 'Russian', 'lang_es': 'Spanish' },
  'pt': { title: 'Base de Conhecimento Uchat', subtitle: 'Faça perguntas à wiki local.', placeholder: 'Insira uma pergunta', teamLabel: 'Equipe (Base de Conhecimento)', langLabel: 'Idioma da resposta', askBtn: 'Perguntar', newConvBtn: 'Nova conversa', hint: 'Perguntas de acompanhamento neste navegador mantêm o contexto da conversa recente. “Nova conversa” limpa esse contexto.', waiting: 'Aguardando o Worker...', healthChecking: 'Verificando o Worker...', healthOnline: 'Worker online', healthOffline: 'Worker offline', signIn: 'Entrar', manageSources: 'Gerenciar fontes', uploadDocs: 'Enviar documentação', newConvStarted: 'Nova conversa iniciada.',
    'lang_zh-CN': 'Chinês Simplificado', 'lang_zh-TW': 'Chinês Tradicional', 'lang_ko': 'Coreano', 'lang_ja': 'Japonês', 'lang_en': 'Inglês', 'lang_pt': 'Português', 'lang_ru': 'Russo', 'lang_es': 'Espanhol' },
  'ru': { title: 'База знаний Uchat', subtitle: 'Задайте вопросы локальной вики.', placeholder: 'Введите вопрос', teamLabel: 'Команда (База знаний)', langLabel: 'Язык ответа', askBtn: 'Спросить', newConvBtn: 'Новый диалог', hint: 'Последующие вопросы в этом браузере сохраняют контекст недавнего диалога. «Новый диалог» очищает этот контекст.', waiting: 'Ожидание Worker...', healthChecking: 'Проверка Worker...', healthOnline: 'Worker онлайн', healthOffline: 'Worker оффлайн', signIn: 'Войти', manageSources: 'Управление источниками', uploadDocs: 'Загрузить документацию', newConvStarted: 'Начат новый диалог.',
    'lang_zh-CN': 'Китайский (упрощенный)', 'lang_zh-TW': 'Китайский (традиционный)', 'lang_ko': 'Корейский', 'lang_ja': 'Японский', 'lang_en': 'Английский', 'lang_pt': 'Португальский', 'lang_ru': 'Русский', 'lang_es': 'Испанский' },
  'es': { title: 'Base de Conocimiento Uchat', subtitle: 'Haga preguntas a la wiki local.', placeholder: 'Introduzca una pregunta', teamLabel: 'Equipo (Base de Conocimiento)', langLabel: 'Idioma de la respuesta', askBtn: 'Preguntar', newConvBtn: 'Nueva conversación', hint: 'Las preguntas de seguimiento en este navegador mantienen el contexto reciente. “Nueva conversación” borra ese contexto.', waiting: 'Esperando al Worker...', healthChecking: 'Comprobando Worker...', healthOnline: 'Worker en línea', healthOffline: 'Worker desconectado', signIn: 'Iniciar sesión', manageSources: 'Administrar fuentes', uploadDocs: 'Subir documentación', newConvStarted: 'Nueva conversación iniciada.',
    'lang_zh-CN': 'Chino Simplificado', 'lang_zh-TW': 'Chino Tradicional', 'lang_ko': 'Coreano', 'lang_ja': 'Japonés', 'lang_en': 'Inglés', 'lang_pt': 'Portugués', 'lang_ru': 'Ruso', 'lang_es': 'Español' }
};
"""

print("Scripts created.")
