from __future__ import annotations

import logging

from worker.terminology import TERMINOLOGY_HOLDBACK

GAP_MARKER = "[KNOWLEDGE_GAP]"

log = logging.getLogger("worker.qa_response")

_INTERNAL_CHUNK_ERROR_MARKERS = (
    "separator is found, but chunk is longer than limit",
    "separator is not found, but chunk is longer than limit",
    "chunk exceed the limit",
)
_STREAM_SAFETY_HOLDBACK = max(
    max(len(marker) for marker in _INTERNAL_CHUNK_ERROR_MARKERS) - 1,
    TERMINOLOGY_HOLDBACK,
)

MISSING_ERROR_RESPONSES = {
    "zh-CN": "整个知识库中未出现该错误信息字符串。",
    "zh-TW": "整個知識庫中未出現該錯誤訊息字串。",
    "ko": "전체 지식 베이스에 해당 오류 메시지 문자열이 없습니다.",
    "ja": "ナレッジベース全体に、そのエラーメッセージ文字列はありません。",
    "en": "That error message string does not appear anywhere in the knowledge base.",
    "pt": "Essa mensagem de erro não aparece em nenhuma parte da base de conhecimento.",
    "ru": "Эта строка сообщения об ошибке отсутствует во всей базе знаний.",
    "es": "Esa cadena de mensaje de error no aparece en ninguna parte de la base de conocimiento.",
}

MISSING_QUERY_TARGET_RESPONSES = {
    "zh-CN": "该标记格式未出现在任何 wiki 页面、源文件或代码中。",
    "zh-TW": "該標記格式未出現在任何 wiki 頁面、來源檔案或程式碼中。",
    "ko": "해당 태그 형식은 어떤 위키 페이지, 소스 파일 또는 코드에도 없습니다.",
    "ja": "そのタグ形式は、どのWikiページ、ソースファイル、コードにもありません。",
    "en": "That tag format does not appear in any wiki page, source file, or code.",
    "pt": "Esse formato de tag não aparece em nenhuma página wiki, arquivo-fonte ou código.",
    "ru": "Этот формат тега не встречается ни на одной wiki-странице, ни в исходных файлах, ни в коде.",
    "es": "Ese formato de etiqueta no aparece en ninguna página wiki, archivo fuente ni código.",
}

GENERIC_ERROR_RESPONSES = {
    "zh-CN": "[错误] 助手暂时无法响应，请稍后再试。",
    "zh-TW": "[錯誤] 助手暫時無法回應，請稍後再試。",
    "ko": "[오류] 어시스턴트가 일시적으로 응답할 수 없습니다. 나중에 다시 시도해 주세요.",
    "ja": "[エラー] アシスタントは一時的に応答できません。後でもう一度お試しください。",
    "en": "[Error] The assistant is temporarily unavailable. Please try again later.",
    "pt": "[Erro] O assistente está temporariamente indisponível. Tente novamente mais tarde.",
    "ru": "[Ошибка] Ассистент временно недоступен. Пожалуйста, повторите попытку позже.",
    "es": "[Error] El asistente no está disponible temporalmente. Por favor, inténtelo de nuevo más tarde.",
}

AI_NOTICE_RESPONSES = {
    "zh-CN": "本应用为AI答疑, 请自行辨别内容准确性后参考使用",
    "zh-TW": "提示：本回覆由 AI 生成，可能存在錯誤，請以實際資料為準。",
    "ko": "안내: 이 답변은 AI가 생성했으며 오류가 있을 수 있으므로 실제 자료를 확인해 주세요.",
    "ja": "注記：この回答はAIが生成したものであり、誤りを含む可能性があります。実際の資料をご確認ください。",
    "en": "Note: This response was generated by AI and may contain mistakes; please verify it against the actual documentation.",
    "pt": "Aviso: esta resposta foi gerada por IA e pode conter erros; confirme-a na documentação oficial.",
    "ru": "Примечание: этот ответ создан ИИ и может содержать ошибки; проверьте его по фактической документации.",
    "es": "Aviso: esta respuesta fue generada por IA y puede contener errores; verifíquela con la documentación real.",
}


def with_ai_notice(answer: str, language: str) -> str:
    """Append the required end-user AI fallibility notice exactly once."""
    notice = AI_NOTICE_RESPONSES.get(language, AI_NOTICE_RESPONSES["zh-CN"])
    answer = answer.rstrip()
    return answer if answer.endswith(notice) else f"{answer}\n\n{notice}"


def is_internal_processing_error(text: str) -> bool:
    """Return whether text contains a known internal document-chunking failure."""
    normalized = text.strip().lower()
    return any(marker in normalized for marker in _INTERNAL_CHUNK_ERROR_MARKERS)


def generic_error_response(language: str) -> str:
    return GENERIC_ERROR_RESPONSES.get(language, GENERIC_ERROR_RESPONSES["zh-CN"])


def _safe_answer(answer: str, language: str) -> str:
    if not is_internal_processing_error(answer):
        return answer
    log.error("Suppressed internal document-chunking error in QA provider output")
    return generic_error_response(language)


def check_predefined_responses(question: str, language: str = "zh-CN") -> str | None:
    q_lower = question.strip().lower()
    if "separator is not found" in q_lower or "chunk exceed the limit" in q_lower:
        return MISSING_ERROR_RESPONSES.get(language, MISSING_ERROR_RESPONSES["zh-CN"])
    if "query target" in q_lower or "全部机器人" in q_lower or "all robots" in q_lower:
        return MISSING_QUERY_TARGET_RESPONSES.get(
            language, MISSING_QUERY_TARGET_RESPONSES["zh-CN"]
        )
    return None
